[package]
name = "pipes"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
lazy_static = "1.4.0"
tokio = { version = "1.37", features = ["full"] }
uuid = { version = "1.8.0", features = ["v4"] }
